services:
  - type: web
    name: odoocafe-pos
    env: node
    plan: free
    rootDir: odoocafe
    buildCommand: "pnpm install && npx prisma generate && npx prisma db push && pnpm run build"
    startCommand: "pnpm run start"
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: NEXTAUTH_URL
        sync: false
      - key: NEXT_PUBLIC_APP_URL
        sync: false
      - key: NEXT_PUBLIC_SOCKET_URL
        sync: false
      - key: CUSTOMER_JWT_SECRET
        generateValue: true
      - key: QR_SECRET
        generateValue: true
      - key: SOCKET_SECRET
        generateValue: true
